library("data.table")
library("reshape2")
library("dplyr")
library("magrittr")
library("stringr")
library("ggplot2")
library("R6")
library("shiny")
library("plotly")
library("DT")
library("Matrix")
#setRepositories(ind = 1,addURLs = c(BioC = "https://bioconductor.org/packages/3.8/bioc"))
library("biomaRt")
source("Functions.R", local=TRUE)
source("Class.R", local=TRUE)

NCBP <- Template$new()
NCBP$enrichProteinPerTarget("target")
save(NCBP, file="db/target.RData")
NCBP$enrichProteinPerTarget("group")
save(NCBP, file="db/group.RData")
